version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install pytest
  build:
    commands:
      - ls -l
      - export PYTHONPATH=$(pwd)
      - echo $PYTHONPATH
      - echo "Running pytest..."
      - pytest --maxfail=1 --disable-warnings -v
  post_build:
    commands:
      - echo "Tests passed - preparing artifact..."
      - mkdir -p deploy
      - cp -r * deploy/
artifacts:
  files:
    - '**/*'
  base-directory: deploy
  discard-paths: no
